apiVersion: v1
kind: Pod
metadata:
    name: dbpopulator-pod
    labels:
       app: web
       env: test
spec:
     containers:
        - name: dbpopulator
          image: gcr.io/vaulted-zodiac-236605/dbpopulator
          command: ["python"]
          args: ["/home/WatchDogs_DatabasePopulator/populate_db.py"]

